### ISSUE TITLE
Issue with Folders in Filezilla

### ISSUE THREAD

**Issue by RLG95** [BMT45/Ferdinand-Magellan-Project#7]
I have had a few issues creating a hierarchy of folders in the server, anytime I put in any of the files, the links from the index become broken. I don't know what to do.

**Comment by ebeshero** [comment]
@RLG95 Aha! I think the problem is that you need to edit your links to account for the new folders. So, let's say you created folder you've named `voyageLogs`, and you place a file named `magellan.xml` in it. Your `index.html` page is probably sitting out in the main directory of `public_html`, right? If you have a link on your `index.html` page leading down into the voyageLogs folder, that directory name needs to be in your relative filepath. That means, a link from `index.html` leading to `magellan.xml` needs to look like this:

```
<a href="voyageLogs/magellan.xml">Magellan XML file</a>
```

Does that help? The file directory structure translates into a new step in your link path.

**Comment by ebeshero** [comment]
@RLG95 I'll take a look at your project file directories in case the problem is something else--it occurs to me that this could also be a file permissions issue...

**Comment by RLG95** [comment]
Still slightly confused but I will try it

**Comment by ebeshero** [comment]
@RLG95 Hmm...well, there's a file permissions issue with the new files on the server. (This is pretty common when uploading files to a shared group directory.) The files uploaded in Magellan all have rw-r--r-- permissions, which means the owner can read and write, and the group and public can only read. (That's okay, but if you have server-side includes to control a menu on the site, they won't work with these permissions.) We want to make the permissions be rwxrwxr-x.  You may be able to change this on your end, or I can do it from here.

**Comment by ebeshero** [comment]
@RLG95 I don't think the file permissions are the reason for the broken links, since everyone *does* have read permission. Once you create folders in the Magellan web space on newtFire, change your links to point down into the folders. 
```
<a href="folderName/fileName.html"/>
```
That's an example of a *relative link*, which means that the link points to a new file *in relation to the current file.* If index.html is out in the main directory, you need to give the directory name in which you're storing the file. (And of course that'll only work when you have directories set up.)

**Comment by RLG95** [comment]
I finally got the links to not be broken, however now the top disappears on everything but the home page?

**Comment by ebeshero** [comment]
@RLG95 If you are using server side includes (SSI's) to standardize the top part of your pages, I bet there's something that needs to be modified. Where is the SSI in relation to the web pages--did the location change?

**Comment by RLG95** [comment]
My top.html (SSI) is sitting out in my main directory where I put everything else into folders.

**Comment by ebeshero** [comment]
@RLG95 I bet you need to change the way you are referencing the SSI file inside your HTML files, if you've moved those into their own directories. If I understand how you're organizing things, I think the filepath will look something like this:

```
../yourSSI.html
```
The `../` climbs up into a parent directory.
